/* Automatically generated by configure - do not modify */
#define TUNECPU generic
#define HAVE_BUILTIN_VECTOR 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LRINTF 1
#define CONFIG_ENCODERS 1
#define CONFIG_DECODERS 1
#define CONFIG_HAVE_DLOPEN 1
#define CONFIG_HAVE_DLFCN 1
#define CONFIG_ZLIB 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMALIGN 1
#define CONFIG_RISKY 1
#define restrict __restrict__
